services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-sun-energy-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_dG91Y2hpbmctcGhvZW5peC04My5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_AvDWCmPzsOZaam8C8psdVVYXRlgTWZ8jFe57RwlvfG
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/auth/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/auth/sign-up
      - SMTP_SERVER_USERNAME=omanpple42@gmail.com
      - SMTP_SERVER_PASSWORD=Om120600!
      - SMTP_SERVER_HOST=email-smtp.us-east-1.amazonaws.com
      - SITE_MAIL_RECIEVER="mail-receiver-email"
      - NEXT_PUBLIC_API_URL=http://localhost:3001
